[build]
builder = "DOCKERFILE"
dockerfilePath = "apps/backend/Dockerfile"
buildCommand = "echo 'Building backend...'"

[deploy]
startCommand = "cd apps/backend && alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
